package main

const templateTests = `
// Code generated by go-featureprocessing DO NOT EDIT

package {{$.PackageName}}

import (
	"encoding/json"
	"testing"

	"github.com/google/gofuzz"
	"github.com/stretchr/testify/assert"
)

// makeMock creates some valid {{$.StructName}}FeatureTransformer by fitting on fuzzy data.
// This function is handy for tests.
func makeMock{{$.StructName}}FeatureTransformer() *{{$.StructName}}FeatureTransformer {
	s := make([]{{$.StructName}}, 10)
	fuzz.New().NilChance(0).NumElements(10, 10).Fuzz(&s)
	
	tr := {{$.StructName}}FeatureTransformer{}
	tr.Fit(s)
	return &tr
}

func Test{{$.StructName}}FeatureTransformerFeatureNames(t *testing.T) {
	tr := makeMock{{$.StructName}}FeatureTransformer()

	t.Run("feature names", func(t *testing.T) {
		names := tr.FeatureNames()
		assert.True(t, len(names) > 0)
		assert.Equal(t, len(names), tr.NumFeatures())
	})

	t.Run("feature name transformer is empty", func(t *testing.T) {
		tr := {{$.StructName}}FeatureTransformer{}
		names := tr.FeatureNames()
		assert.True(t, len(names) > 0)
		assert.Equal(t, len(names), tr.NumFeatures())
	})

	t.Run("feature name transformer is nil", func(t *testing.T) {
		var tr *{{$.StructName}}FeatureTransformer
		names := tr.FeatureNames()
		assert.Nil(t, names)
	})
}

func Test{{$.StructName}}FeatureTransformerTransform(t *testing.T) {
	tr := makeMock{{$.StructName}}FeatureTransformer()

	t.Run("empty struct", func(t *testing.T) {
		s := {{$.StructName}}{}
		features := tr.Transform(&s)

		assert.NotNil(t, features)
		assert.True(t, len(features) > 0)
		assert.Equal(t, tr.NumFeatures(), len(features))
	})

	t.Run("fuzzy struct", func(t *testing.T) {
		var s {{$.StructName}}
		fuzz.New().Fuzz(&s)
		
		tr := {{$.StructName}}FeatureTransformer{}
		fuzz.New().NilChance(0).NumElements(1, 1).Fuzz(&tr)

		features := tr.Transform(&s)

		assert.NotNil(t, features)
		assert.True(t, len(features) > 0)
		assert.Equal(t, tr.NumFeatures(), len(features))
	})

	t.Run("struct is nil", func(t *testing.T) {
		var s *{{$.StructName}}
		features := tr.Transform(s)
		assert.Nil(t, features)
		assert.True(t, tr.NumFeatures() > 0)
	})

	t.Run("transformer is nil", func(t *testing.T) {
		var s {{$.StructName}}
		fuzz.New().Fuzz(&s)
		
		var tr *{{$.StructName}}FeatureTransformer
		features := tr.Transform(&s)

		assert.Nil(t, features)
		assert.Equal(t, tr.NumFeatures(), 0)
	})

	t.Run("serialize and deserialize transformer", func(t *testing.T) {
		output, err := json.Marshal(tr)
		assert.Nil(t, err)
		assert.NotEmpty(t, output)
		
		var tr2 {{$.StructName}}FeatureTransformer
		err = json.Unmarshal(output, &tr2)
		assert.Nil(t, err)
		assert.Equal(t, *tr, tr2)
	})

	t.Run("inplace transform does not run when destination does not match num features", func(t *testing.T) {
		var s {{$.StructName}}
		fuzz.New().Fuzz(&s)
		
		tr := {{$.StructName}}FeatureTransformer{}

		features := make([]float64, 1000)
		features[0] = 123456789.0
		tr.TransformInplace(features, &s)

		assert.Equal(t, 123456789.0, features[0])
	})
}

func Test{{$.StructName}}FeatureTransformerTransformAll(t *testing.T) {
	t.Run("when transformer is nil", func(t *testing.T) {
		s := make([]{{$.StructName}}, 100)
		fuzz.New().NilChance(0).NumElements(100, 100).Fuzz(&s)

		dst := make([]float64, 100 * 100)

		var tr *{{$.StructName}}FeatureTransformer
		assert.Nil(t, tr.TransformAll(s))
		assert.Nil(t, tr.TransformAllParallel(s, 4))
		
		// does not panic
		tr.TransformAllInplace(dst, s)
		tr.TransformAllInplaceParallel(dst, s, 4)
	})
	
	t.Run("inplace with wrong output dimensions, output is smaller", func(t *testing.T) {
		s := make([]{{$.StructName}}, 100)
		fuzz.New().NilChance(0).NumElements(100, 100).Fuzz(&s)

		dst := make([]float64, 100)

		tr := makeMock{{$.StructName}}FeatureTransformer()
		
		// does not panic
		tr.TransformAllInplace(dst, s)
		tr.TransformAllInplaceParallel(dst, s, 4)
	})
	
	t.Run("inplace with wrong output dimensions, output is bigger", func(t *testing.T) {
		s := make([]{{$.StructName}}, 100)
		fuzz.New().NilChance(0).NumElements(100, 100).Fuzz(&s)

		dst := make([]float64, 100 * 120)

		tr := makeMock{{$.StructName}}FeatureTransformer()
		
		// does not panic
		tr.TransformAllInplace(dst, s)
		tr.TransformAllInplaceParallel(dst, s, 4)
	})

	t.Run("transform all", func(t *testing.T) {
		s := make([]{{$.StructName}}, 100)
		fuzz.New().NilChance(0).NumElements(100, 100).Fuzz(&s)
		
		tr := makeMock{{$.StructName}}FeatureTransformer()

		features := tr.TransformAll(s)
		assert.Equal(t, len(s) * tr.NumFeatures(), len(features))
	})
	
	t.Run("transform all parallel 1 worker", func(t *testing.T) {
		s := make([]{{$.StructName}}, 100)
		fuzz.New().NilChance(0).NumElements(100, 100).Fuzz(&s)
		
		tr := makeMock{{$.StructName}}FeatureTransformer()

		features := tr.TransformAllParallel(s, 1)
		assert.Equal(t, len(s) * tr.NumFeatures(), len(features))
	})
	
	t.Run("transform all parallel 4 workers", func(t *testing.T) {
		s := make([]{{$.StructName}}, 100)
		fuzz.New().NilChance(0).NumElements(100, 100).Fuzz(&s)
		
		tr := makeMock{{$.StructName}}FeatureTransformer()

		features := tr.TransformAllParallel(s, 4)
		assert.Equal(t, len(s) * tr.NumFeatures(), len(features))
	})
}

func Test{{$.StructName}}FeatureTransformerFit(t *testing.T) {
	t.Run("fuzzy input", func(t *testing.T) {
		s := make([]{{$.StructName}}, 10)
		fuzz.New().NilChance(0).NumElements(1, 1).Fuzz(&s)
		
		trEmpty := {{$.StructName}}FeatureTransformer{}
		tr := {{$.StructName}}FeatureTransformer{}
		tr.Fit(s)

		assert.NotNil(t, tr)
		assert.NotEqual(t, tr, trEmpty)
	})

	t.Run("not nil transformer nil input", func(t *testing.T) {
		trEmpty := {{$.StructName}}FeatureTransformer{}
		tr := {{$.StructName}}FeatureTransformer{}
		tr.Fit(nil)

		assert.Equal(t, trEmpty, tr)
	})

	t.Run("nil transformer not nil input", func(t *testing.T) {
		s := make([]{{$.StructName}}, 10)
		
		var tr *{{$.StructName}}FeatureTransformer
		tr.Fit(s)

		assert.Nil(t, tr)
	})
}

func fitTransformer{{$.StructName}}(b *testing.B, numelem int) {
	s := make([]{{$.StructName}}, numelem)
	fuzz.New().NilChance(0).NumElements(numelem, numelem).Fuzz(&s)
	
	var tr {{$.StructName}}FeatureTransformer

	b.ResetTimer()
	for n := 0; n < b.N; n++ {
		tr.Fit(s)
	}
}

func Benchmark{{$.StructName}}FeatureTransformer_Fit_100elements(b *testing.B) {
	fitTransformer{{$.StructName}}(b, 100)
}

func Benchmark{{$.StructName}}FeatureTransformer_Fit_1000elements(b *testing.B) {
	fitTransformer{{$.StructName}}(b, 1000)
}

func Benchmark{{$.StructName}}FeatureTransformer_Fit_10000elements(b *testing.B) {
	fitTransformer{{$.StructName}}(b, 10000)
}

func Benchmark{{$.StructName}}FeatureTransformer_Transform(b *testing.B) {
	var s {{$.StructName}}
	fuzz.New().Fuzz(&s)
	
	tr := makeMock{{$.StructName}}FeatureTransformer()

	b.ResetTimer()
	for n := 0; n < b.N; n++ {
		tr.Transform(&s)
	}
}

func Benchmark{{$.StructName}}FeatureTransformer_Transform_Inplace(b *testing.B) {
	var s {{$.StructName}}
	fuzz.New().Fuzz(&s)
	
	tr := makeMock{{$.StructName}}FeatureTransformer()

	features := make([]float64, tr.NumFeatures())

	b.ResetTimer()
	for n := 0; n < b.N; n++ {
		tr.TransformInplace(features, &s)
	}
}

func benchTransformAll{{$.StructName}}(b *testing.B, numelem int) {
	s := make([]{{$.StructName}}, numelem)
	fuzz.New().NilChance(0).NumElements(numelem, numelem).Fuzz(&s)
	
	tr := makeMock{{$.StructName}}FeatureTransformer()

	b.ResetTimer()
	for n := 0; n < b.N; n++ {
		tr.TransformAll(s)
	}
}

func Benchmark{{$.StructName}}FeatureTransformer_TransformAll_10elems(b *testing.B) {
	benchTransformAll{{$.StructName}}(b, 10)
}

func Benchmark{{$.StructName}}FeatureTransformer_TransformAll_100elems(b *testing.B) {
	benchTransformAll{{$.StructName}}(b, 100)
}

func Benchmark{{$.StructName}}FeatureTransformer_TransformAll_1000elems(b *testing.B) {
	benchTransformAll{{$.StructName}}(b, 1000)
}

func Benchmark{{$.StructName}}FeatureTransformer_TransformAll_10000elems(b *testing.B) {
	benchTransformAll{{$.StructName}}(b, 10000)
}

func Benchmark{{$.StructName}}FeatureTransformer_TransformAll_100000elems(b *testing.B) {
	benchTransformAll{{$.StructName}}(b, 100000)
}

func Benchmark{{$.StructName}}FeatureTransformer_TransformAll_1000000elems(b *testing.B) {
	benchTransformAll{{$.StructName}}(b, 1000000)
}

func benchTransformAllParallel{{$.StructName}}(b *testing.B, numelem int, nworkers uint) {
	s := make([]{{$.StructName}}, numelem)
	fuzz.New().NilChance(0).NumElements(numelem, numelem).Fuzz(&s)
	
	tr := makeMock{{$.StructName}}FeatureTransformer()

	b.ResetTimer()
	for n := 0; n < b.N; n++ {
		tr.TransformAllParallel(s, nworkers)
	}
}

func Benchmark{{$.StructName}}FeatureTransformer_TransformAll_10elems_8workers(b *testing.B) {
	benchTransformAllParallel{{$.StructName}}(b, 10, 8)
}

func Benchmark{{$.StructName}}FeatureTransformer_TransformAll_100elems_8workers(b *testing.B) {
	benchTransformAllParallel{{$.StructName}}(b, 100, 8)
}

func Benchmark{{$.StructName}}FeatureTransformer_TransformAll_1000elems_8workers(b *testing.B) {
	benchTransformAllParallel{{$.StructName}}(b, 1000, 8)
}

func Benchmark{{$.StructName}}FeatureTransformer_TransformAll_10000elems_8workers(b *testing.B) {
	benchTransformAllParallel{{$.StructName}}(b, 10000, 8)
}

func Benchmark{{$.StructName}}FeatureTransformer_TransformAll_100000elems_8workers(b *testing.B) {
	benchTransformAllParallel{{$.StructName}}(b, 100000, 8)
}

func Benchmark{{$.StructName}}FeatureTransformer_TransformAll_1000000elems_8workers(b *testing.B) {
	benchTransformAllParallel{{$.StructName}}(b, 1000000, 8)
}

func Benchmark{{$.StructName}}FeatureTransformer_TransformAll_5000000elems_8workers(b *testing.B) {
	benchTransformAllParallel{{$.StructName}}(b, 5000000, 8)
}

func Benchmark{{$.StructName}}FeatureTransformer_TransformAll_15000000elems_8workers(b *testing.B) {
	benchTransformAllParallel{{$.StructName}}(b, 15000000, 8)
}

{{if $.HasLargeTransformers}}

func benchLargeTransformer{{$.StructName}}(b *testing.B, numelem int) {
	var s []{{$.StructName}}
	fuzz.New().NilChance(0).NumElements(numelem, numelem).Fuzz(&s)
	
	tr := {{$.StructName}}FeatureTransformer{}
	tr.Fit(s)

	b.ResetTimer()
	for n := 0; n < b.N; n++ {
		tr.Transform(&s[0])
	}
}

func Benchmark{{$.StructName}}FeatureTransformer_Transform_LargeComposites_100elements(b *testing.B) {
	benchLargeTransformer{{$.StructName}}(b, 100)
}

func Benchmark{{$.StructName}}FeatureTransformer_Transform_LargeComposites_1000elements(b *testing.B) {
	benchLargeTransformer{{$.StructName}}(b, 1000)
}

func Benchmark{{$.StructName}}FeatureTransformer_Transform_LargeComposites_10000elements(b *testing.B) {
	benchLargeTransformer{{$.StructName}}(b, 10000)
}

func Benchmark{{$.StructName}}FeatureTransformer_Transform_LargeComposites_100000elements(b *testing.B) {
	benchLargeTransformer{{$.StructName}}(b, 100000)
}

{{end}}
`
