// Code generated by go-featureprocessing DO NOT EDIT

package examplemodule

import (
	"encoding/json"
	"testing"

	"github.com/google/gofuzz"
	"github.com/stretchr/testify/assert"
)

// makeMock creates some valid AllTransformersFeatureTransformer by fitting on fuzzy data.
// This function is handy for tests.
func makeMockAllTransformersFeatureTransformer() *AllTransformersFeatureTransformer {
	s := make([]AllTransformers, 10)
	fuzz.New().NilChance(0).NumElements(10, 10).Fuzz(&s)

	tr := AllTransformersFeatureTransformer{}
	tr.Fit(s)
	return &tr
}

func TestAllTransformersFeatureTransformerFeatureNames(t *testing.T) {
	tr := makeMockAllTransformersFeatureTransformer()

	t.Run("feature names", func(t *testing.T) {
		names := tr.FeatureNames()
		assert.True(t, len(names) > 0)
		assert.Equal(t, len(names), tr.NumFeatures())
	})

	t.Run("feature name transformer is empty", func(t *testing.T) {
		tr := AllTransformersFeatureTransformer{}
		names := tr.FeatureNames()
		assert.True(t, len(names) > 0)
		assert.Equal(t, len(names), tr.NumFeatures())
	})

	t.Run("feature name transformer is nil", func(t *testing.T) {
		var tr *AllTransformersFeatureTransformer
		names := tr.FeatureNames()
		assert.Nil(t, names)
	})
}

func TestAllTransformersFeatureTransformerTransform(t *testing.T) {
	tr := makeMockAllTransformersFeatureTransformer()

	t.Run("empty struct", func(t *testing.T) {
		s := AllTransformers{}
		features := tr.Transform(&s)

		assert.NotNil(t, features)
		assert.True(t, len(features) > 0)
		assert.Equal(t, tr.NumFeatures(), len(features))
	})

	t.Run("fuzzy struct", func(t *testing.T) {
		var s AllTransformers
		fuzz.New().Fuzz(&s)

		tr := AllTransformersFeatureTransformer{}
		fuzz.New().NilChance(0).NumElements(1, 1).Fuzz(&tr)

		features := tr.Transform(&s)

		assert.NotNil(t, features)
		assert.True(t, len(features) > 0)
		assert.Equal(t, tr.NumFeatures(), len(features))
	})

	t.Run("struct is nil", func(t *testing.T) {
		var s *AllTransformers
		features := tr.Transform(s)
		assert.Nil(t, features)
		assert.True(t, tr.NumFeatures() > 0)
	})

	t.Run("transformer is nil", func(t *testing.T) {
		var s AllTransformers
		fuzz.New().Fuzz(&s)

		var tr *AllTransformersFeatureTransformer
		features := tr.Transform(&s)

		assert.Nil(t, features)
		assert.Equal(t, tr.NumFeatures(), 0)
	})

	t.Run("serialize and deserialize transformer", func(t *testing.T) {
		output, err := json.Marshal(tr)
		assert.Nil(t, err)
		assert.NotEmpty(t, output)

		var tr2 AllTransformersFeatureTransformer
		err = json.Unmarshal(output, &tr2)
		assert.Nil(t, err)
		assert.Equal(t, *tr, tr2)
	})

	t.Run("inplace transform does not run when destination does not match num features", func(t *testing.T) {
		var s AllTransformers
		fuzz.New().Fuzz(&s)

		tr := AllTransformersFeatureTransformer{}

		features := make([]float64, 1000)
		features[0] = 123456789.0
		tr.TransformInplace(features, &s)

		assert.Equal(t, 123456789.0, features[0])
	})
}

func TestAllTransformersFeatureTransformerTransformAll(t *testing.T) {
	t.Run("when transformer is nil", func(t *testing.T) {
		s := make([]AllTransformers, 100)
		fuzz.New().NilChance(0).NumElements(100, 100).Fuzz(&s)

		dst := make([]float64, 100*100)

		var tr *AllTransformersFeatureTransformer
		assert.Nil(t, tr.TransformAll(s))
		assert.Nil(t, tr.TransformAllParallel(s, 4))

		// does not panic
		tr.TransformAllInplace(dst, s)
		tr.TransformAllInplaceParallel(dst, s, 4)
	})

	t.Run("inplace with wrong output dimensions, output is smaller", func(t *testing.T) {
		s := make([]AllTransformers, 100)
		fuzz.New().NilChance(0).NumElements(100, 100).Fuzz(&s)

		dst := make([]float64, 100)

		tr := makeMockAllTransformersFeatureTransformer()

		// does not panic
		tr.TransformAllInplace(dst, s)
		tr.TransformAllInplaceParallel(dst, s, 4)
	})

	t.Run("inplace with wrong output dimensions, output is bigger", func(t *testing.T) {
		s := make([]AllTransformers, 100)
		fuzz.New().NilChance(0).NumElements(100, 100).Fuzz(&s)

		dst := make([]float64, 100*120)

		tr := makeMockAllTransformersFeatureTransformer()

		// does not panic
		tr.TransformAllInplace(dst, s)
		tr.TransformAllInplaceParallel(dst, s, 4)
	})

	t.Run("transform all", func(t *testing.T) {
		s := make([]AllTransformers, 100)
		fuzz.New().NilChance(0).NumElements(100, 100).Fuzz(&s)

		tr := makeMockAllTransformersFeatureTransformer()

		features := tr.TransformAll(s)
		assert.Equal(t, len(s)*tr.NumFeatures(), len(features))
	})

	t.Run("transform all parallel 1 worker", func(t *testing.T) {
		s := make([]AllTransformers, 100)
		fuzz.New().NilChance(0).NumElements(100, 100).Fuzz(&s)

		tr := makeMockAllTransformersFeatureTransformer()

		features := tr.TransformAllParallel(s, 1)
		assert.Equal(t, len(s)*tr.NumFeatures(), len(features))
	})

	t.Run("transform all parallel 4 workers", func(t *testing.T) {
		s := make([]AllTransformers, 100)
		fuzz.New().NilChance(0).NumElements(100, 100).Fuzz(&s)

		tr := makeMockAllTransformersFeatureTransformer()

		features := tr.TransformAllParallel(s, 4)
		assert.Equal(t, len(s)*tr.NumFeatures(), len(features))
	})
}

func TestAllTransformersFeatureTransformerFit(t *testing.T) {
	t.Run("fuzzy input", func(t *testing.T) {
		s := make([]AllTransformers, 10)
		fuzz.New().NilChance(0).NumElements(1, 1).Fuzz(&s)

		trEmpty := AllTransformersFeatureTransformer{}
		tr := AllTransformersFeatureTransformer{}
		tr.Fit(s)

		assert.NotNil(t, tr)
		assert.NotEqual(t, tr, trEmpty)
	})

	t.Run("not nil transformer nil input", func(t *testing.T) {
		trEmpty := AllTransformersFeatureTransformer{}
		tr := AllTransformersFeatureTransformer{}
		tr.Fit(nil)

		assert.Equal(t, trEmpty, tr)
	})

	t.Run("nil transformer not nil input", func(t *testing.T) {
		s := make([]AllTransformers, 10)

		var tr *AllTransformersFeatureTransformer
		tr.Fit(s)

		assert.Nil(t, tr)
	})
}

func fitTransformerAllTransformers(b *testing.B, numelem int) {
	s := make([]AllTransformers, numelem)
	fuzz.New().NilChance(0).NumElements(numelem, numelem).Fuzz(&s)

	var tr AllTransformersFeatureTransformer

	b.ResetTimer()
	for n := 0; n < b.N; n++ {
		tr.Fit(s)
	}
}

func BenchmarkAllTransformersFeatureTransformer_Fit_100elements(b *testing.B) {
	fitTransformerAllTransformers(b, 100)
}

func BenchmarkAllTransformersFeatureTransformer_Fit_1000elements(b *testing.B) {
	fitTransformerAllTransformers(b, 1000)
}

func BenchmarkAllTransformersFeatureTransformer_Fit_10000elements(b *testing.B) {
	fitTransformerAllTransformers(b, 10000)
}

func BenchmarkAllTransformersFeatureTransformer_Transform(b *testing.B) {
	var s AllTransformers
	fuzz.New().Fuzz(&s)

	tr := makeMockAllTransformersFeatureTransformer()

	b.ResetTimer()
	for n := 0; n < b.N; n++ {
		tr.Transform(&s)
	}
}

func BenchmarkAllTransformersFeatureTransformer_Transform_Inplace(b *testing.B) {
	var s AllTransformers
	fuzz.New().Fuzz(&s)

	tr := makeMockAllTransformersFeatureTransformer()

	features := make([]float64, tr.NumFeatures())

	b.ResetTimer()
	for n := 0; n < b.N; n++ {
		tr.TransformInplace(features, &s)
	}
}

func benchTransformAllAllTransformers(b *testing.B, numelem int) {
	s := make([]AllTransformers, numelem)
	fuzz.New().NilChance(0).NumElements(numelem, numelem).Fuzz(&s)

	tr := makeMockAllTransformersFeatureTransformer()

	b.ResetTimer()
	for n := 0; n < b.N; n++ {
		tr.TransformAll(s)
	}
}

func BenchmarkAllTransformersFeatureTransformer_TransformAll_10elems(b *testing.B) {
	benchTransformAllAllTransformers(b, 10)
}

func BenchmarkAllTransformersFeatureTransformer_TransformAll_100elems(b *testing.B) {
	benchTransformAllAllTransformers(b, 100)
}

func BenchmarkAllTransformersFeatureTransformer_TransformAll_1000elems(b *testing.B) {
	benchTransformAllAllTransformers(b, 1000)
}

func BenchmarkAllTransformersFeatureTransformer_TransformAll_10000elems(b *testing.B) {
	benchTransformAllAllTransformers(b, 10000)
}

func BenchmarkAllTransformersFeatureTransformer_TransformAll_100000elems(b *testing.B) {
	benchTransformAllAllTransformers(b, 100000)
}

func BenchmarkAllTransformersFeatureTransformer_TransformAll_1000000elems(b *testing.B) {
	benchTransformAllAllTransformers(b, 1000000)
}

func benchTransformAllParallelAllTransformers(b *testing.B, numelem int, nworkers uint) {
	s := make([]AllTransformers, numelem)
	fuzz.New().NilChance(0).NumElements(numelem, numelem).Fuzz(&s)

	tr := makeMockAllTransformersFeatureTransformer()

	b.ResetTimer()
	for n := 0; n < b.N; n++ {
		tr.TransformAllParallel(s, nworkers)
	}
}

func BenchmarkAllTransformersFeatureTransformer_TransformAll_10elems_8workers(b *testing.B) {
	benchTransformAllParallelAllTransformers(b, 10, 8)
}

func BenchmarkAllTransformersFeatureTransformer_TransformAll_100elems_8workers(b *testing.B) {
	benchTransformAllParallelAllTransformers(b, 100, 8)
}

func BenchmarkAllTransformersFeatureTransformer_TransformAll_1000elems_8workers(b *testing.B) {
	benchTransformAllParallelAllTransformers(b, 1000, 8)
}

func BenchmarkAllTransformersFeatureTransformer_TransformAll_10000elems_8workers(b *testing.B) {
	benchTransformAllParallelAllTransformers(b, 10000, 8)
}

func BenchmarkAllTransformersFeatureTransformer_TransformAll_100000elems_8workers(b *testing.B) {
	benchTransformAllParallelAllTransformers(b, 100000, 8)
}

func BenchmarkAllTransformersFeatureTransformer_TransformAll_1000000elems_8workers(b *testing.B) {
	benchTransformAllParallelAllTransformers(b, 1000000, 8)
}

func BenchmarkAllTransformersFeatureTransformer_TransformAll_5000000elems_8workers(b *testing.B) {
	benchTransformAllParallelAllTransformers(b, 5000000, 8)
}

func BenchmarkAllTransformersFeatureTransformer_TransformAll_15000000elems_8workers(b *testing.B) {
	benchTransformAllParallelAllTransformers(b, 15000000, 8)
}

func benchLargeTransformerAllTransformers(b *testing.B, numelem int) {
	var s []AllTransformers
	fuzz.New().NilChance(0).NumElements(numelem, numelem).Fuzz(&s)

	tr := AllTransformersFeatureTransformer{}
	tr.Fit(s)

	b.ResetTimer()
	for n := 0; n < b.N; n++ {
		tr.Transform(&s[0])
	}
}

func BenchmarkAllTransformersFeatureTransformer_Transform_LargeComposites_100elements(b *testing.B) {
	benchLargeTransformerAllTransformers(b, 100)
}

func BenchmarkAllTransformersFeatureTransformer_Transform_LargeComposites_1000elements(b *testing.B) {
	benchLargeTransformerAllTransformers(b, 1000)
}

func BenchmarkAllTransformersFeatureTransformer_Transform_LargeComposites_10000elements(b *testing.B) {
	benchLargeTransformerAllTransformers(b, 10000)
}

func BenchmarkAllTransformersFeatureTransformer_Transform_LargeComposites_100000elements(b *testing.B) {
	benchLargeTransformerAllTransformers(b, 100000)
}
