// Code generated by go-featureprocessing DO NOT EDIT

package examplemodule

import (
	"encoding/json"
	"testing"

	"github.com/google/gofuzz"
	"github.com/stretchr/testify/assert"
)

// makeMock creates some valid EmployeeFeatureTransformer by fitting on fuzzy data.
// This function is handy for tests.
func makeMockEmployeeFeatureTransformer() *EmployeeFeatureTransformer {
	s := make([]Employee, 1000000)
	fuzz.New().NilChance(0).NumElements(10, 10).Fuzz(&s)

	tr := EmployeeFeatureTransformer{}
	tr.Fit(s)
	return &tr
}

func TestEmployeeFeatureTransformerFeatureNames(t *testing.T) {
	validTransformer := makeMockEmployeeFeatureTransformer()

	fuzzyTransformer := EmployeeFeatureTransformer{}
	fuzz.New().NilChance(0).NumElements(10, 10).Fuzz(&fuzzyTransformer)

	t.Run("feature names", func(t *testing.T) {
		names := validTransformer.FeatureNames()
		assert.True(t, len(names) > 0)
		assert.Equal(t, len(names), validTransformer.NumFeatures())
	})

	t.Run("feature names fuzzy transformer has some feature names", func(t *testing.T) {
		names := fuzzyTransformer.FeatureNames()
		assert.True(t, len(names) > 0)
	})

	t.Run("feature name transformer is empty", func(t *testing.T) {
		tr := EmployeeFeatureTransformer{}
		names := tr.FeatureNames()
		assert.True(t, len(names) > 0)
		assert.Equal(t, len(names), tr.NumFeatures())
	})

	t.Run("feature name transformer is nil", func(t *testing.T) {
		var tr *EmployeeFeatureTransformer
		names := tr.FeatureNames()
		assert.Nil(t, names)
	})
}

func TestEmployeeFeatureTransformerTransform(t *testing.T) {
	t.Run("empty struct fuzzy transformer", func(t *testing.T) {
		s := Employee{}

		tr := EmployeeFeatureTransformer{}
		fuzz.New().NilChance(0).NumElements(1, 1).Fuzz(&tr)

		tr.Transform(&s)

		features := tr.Transform(&s)

		assert.NotNil(t, features)
		assert.True(t, len(features) > 0)
		assert.Equal(t, tr.NumFeatures(), len(features))
	})

	t.Run("fuzzy struct", func(t *testing.T) {
		var s Employee
		fuzz.New().Fuzz(&s)

		tr := EmployeeFeatureTransformer{}
		fuzz.New().NilChance(0).NumElements(1, 1).Fuzz(&tr)

		features := tr.Transform(&s)

		assert.NotNil(t, features)
		assert.True(t, len(features) > 0)
		assert.Equal(t, tr.NumFeatures(), len(features))
	})

	t.Run("transformer is nil and struct is not nil", func(t *testing.T) {
		var s Employee
		fuzz.New().Fuzz(&s)

		var tr *EmployeeFeatureTransformer

		features := tr.Transform(&s)

		assert.Nil(t, features)
		assert.Equal(t, tr.NumFeatures(), 0)
	})

	t.Run("transformer is not nil but struct is nil", func(t *testing.T) {
		var s *Employee

		tr := EmployeeFeatureTransformer{}
		fuzz.New().NilChance(0).NumElements(1, 1).Fuzz(&tr)

		features := tr.Transform(s)

		assert.Nil(t, features)
		assert.True(t, tr.NumFeatures() > 0)
	})

	t.Run("serialize and deserialize transformer", func(t *testing.T) {
		tr := EmployeeFeatureTransformer{}
		fuzz.New().NilChance(0).NumElements(1, 1).Fuzz(&tr)

		output, err := json.Marshal(tr)
		assert.Nil(t, err)
		assert.NotEmpty(t, output)

		var tr2 EmployeeFeatureTransformer
		err = json.Unmarshal(output, &tr2)
		assert.Nil(t, err)
		assert.Equal(t, tr, tr2)
	})

	t.Run("inplace transform does not run when destination does not match num features", func(t *testing.T) {
		var s Employee
		fuzz.New().Fuzz(&s)

		tr := EmployeeFeatureTransformer{}
		fuzz.New().NilChance(0).NumElements(1, 1).Fuzz(&tr)

		features := make([]float64, 1000)
		features[0] = 123456789.0
		tr.TransformInplace(features, &s)

		assert.Equal(t, 123456789.0, features[0])
	})
}

func TestEmployeeFeatureTransformerTransformAll(t *testing.T) {
	t.Run("transform all", func(t *testing.T) {
		s := make([]Employee, 100)
		fuzz.New().NilChance(0).NumElements(100, 100).Fuzz(&s)

		tr := EmployeeFeatureTransformer{}
		fuzz.New().NilChance(0).NumElements(100, 100).Fuzz(&tr)

		features := tr.TransformAll(s)
		assert.Equal(t, len(s)*tr.NumFeatures(), len(features))
	})

	t.Run("transform all parallel 1 worker", func(t *testing.T) {
		s := make([]Employee, 100)
		fuzz.New().NilChance(0).NumElements(100, 100).Fuzz(&s)

		tr := EmployeeFeatureTransformer{}
		fuzz.New().NilChance(0).NumElements(100, 100).Fuzz(&tr)

		features := tr.TransformAllParallel(s, 1)
		assert.Equal(t, len(s)*tr.NumFeatures(), len(features))
	})

	t.Run("transform all parallel 4 workers", func(t *testing.T) {
		s := make([]Employee, 100)
		fuzz.New().NilChance(0).NumElements(100, 100).Fuzz(&s)

		tr := EmployeeFeatureTransformer{}
		fuzz.New().NilChance(0).NumElements(100, 100).Fuzz(&tr)

		features := tr.TransformAllParallel(s, 4)
		assert.Equal(t, len(s)*tr.NumFeatures(), len(features))
	})
}

func TestEmployeeFeatureTransformerFit(t *testing.T) {
	t.Run("fuzzy input", func(t *testing.T) {
		s := make([]Employee, 10)
		fuzz.New().NilChance(0).NumElements(1, 1).Fuzz(&s)

		trEmpty := EmployeeFeatureTransformer{}
		tr := EmployeeFeatureTransformer{}
		tr.Fit(s)

		assert.NotNil(t, tr)
		assert.NotEqual(t, tr, trEmpty)
	})

	t.Run("not nil transformer nil input", func(t *testing.T) {
		trEmpty := EmployeeFeatureTransformer{}
		tr := EmployeeFeatureTransformer{}
		tr.Fit(nil)

		assert.Equal(t, trEmpty, tr)
	})

	t.Run("nil transformer not nil input", func(t *testing.T) {
		s := make([]Employee, 10)

		var tr *EmployeeFeatureTransformer
		tr.Fit(s)

		assert.Nil(t, tr)
	})
}

func fitTransformerEmployee(b *testing.B, numelem int) {
	s := make([]Employee, numelem)
	fuzz.New().NilChance(0).NumElements(numelem, numelem).Fuzz(&s)

	var tr EmployeeFeatureTransformer

	b.ResetTimer()
	for n := 0; n < b.N; n++ {
		tr.Fit(s)
	}
}

func BenchmarkEmployeeFeatureTransformer_Fit_100elements(b *testing.B) {
	fitTransformerEmployee(b, 100)
}

func BenchmarkEmployeeFeatureTransformer_Fit_1000elements(b *testing.B) {
	fitTransformerEmployee(b, 1000)
}

func BenchmarkEmployeeFeatureTransformer_Fit_10000elements(b *testing.B) {
	fitTransformerEmployee(b, 10000)
}

func BenchmarkEmployeeFeatureTransformer_Transform(b *testing.B) {
	var s Employee
	fuzz.New().Fuzz(&s)

	tr := EmployeeFeatureTransformer{}
	fuzz.New().NilChance(0).NumElements(1, 1).Fuzz(&tr)

	b.ResetTimer()
	for n := 0; n < b.N; n++ {
		tr.Transform(&s)
	}
}

func BenchmarkEmployeeFeatureTransformer_Transform_Inplace(b *testing.B) {
	var s Employee
	fuzz.New().Fuzz(&s)

	tr := EmployeeFeatureTransformer{}
	fuzz.New().NilChance(0).NumElements(1, 1).Fuzz(&tr)

	features := make([]float64, tr.NumFeatures())

	b.ResetTimer()
	for n := 0; n < b.N; n++ {
		tr.TransformInplace(features, &s)
	}
}

func benchTransformAllEmployee(b *testing.B, numelem int) {
	s := make([]Employee, numelem)
	fuzz.New().NilChance(0).NumElements(numelem, numelem).Fuzz(&s)

	tr := EmployeeFeatureTransformer{}
	fuzz.New().NilChance(0).NumElements(100, 100).Fuzz(&tr)

	b.ResetTimer()
	for n := 0; n < b.N; n++ {
		tr.TransformAll(s)
	}
}

func BenchmarkEmployeeFeatureTransformer_TransformAll_100elems(b *testing.B) {
	benchTransformAllEmployee(b, 100)
}

func BenchmarkEmployeeFeatureTransformer_TransformAll_1000elems(b *testing.B) {
	benchTransformAllEmployee(b, 1000)
}

func BenchmarkEmployeeFeatureTransformer_TransformAll_10000elems(b *testing.B) {
	benchTransformAllEmployee(b, 10000)
}

func BenchmarkEmployeeFeatureTransformer_TransformAll_100000elems(b *testing.B) {
	benchTransformAllEmployee(b, 100000)
}

func BenchmarkEmployeeFeatureTransformer_TransformAll_1000000elems(b *testing.B) {
	benchTransformAllEmployee(b, 1000000)
}

func benchTransformAllParallelEmployee(b *testing.B, numelem int, nworkers uint) {
	s := make([]Employee, numelem)
	fuzz.New().NilChance(0).NumElements(numelem, numelem).Fuzz(&s)

	tr := EmployeeFeatureTransformer{}
	fuzz.New().NilChance(0).NumElements(100, 100).Fuzz(&tr)

	b.ResetTimer()
	for n := 0; n < b.N; n++ {
		tr.TransformAllParallel(s, nworkers)
	}
}

func BenchmarkEmployeeFeatureTransformer_TransformAll_100elems_8workers(b *testing.B) {
	benchTransformAllParallelEmployee(b, 100, 8)
}

func BenchmarkEmployeeFeatureTransformer_TransformAll_1000elems_8workers(b *testing.B) {
	benchTransformAllParallelEmployee(b, 1000, 8)
}

func BenchmarkEmployeeFeatureTransformer_TransformAll_10000elems_8workers(b *testing.B) {
	benchTransformAllParallelEmployee(b, 10000, 8)
}

func BenchmarkEmployeeFeatureTransformer_TransformAll_100000elems_8workers(b *testing.B) {
	benchTransformAllParallelEmployee(b, 100000, 8)
}

func BenchmarkEmployeeFeatureTransformer_TransformAll_1000000elems_8workers(b *testing.B) {
	benchTransformAllParallelEmployee(b, 1000000, 8)
}

func benchLargeTransformerEmployee(b *testing.B, numelem int) {
	var s Employee
	fuzz.New().Fuzz(&s)

	tr := EmployeeFeatureTransformer{}
	fuzz.New().NilChance(0).NumElements(numelem, numelem).Fuzz(&tr)

	b.ResetTimer()
	for n := 0; n < b.N; n++ {
		tr.Transform(&s)
	}
}

func BenchmarkEmployeeFeatureTransformer_Transform_LargeComposites_100elements(b *testing.B) {
	benchLargeTransformerEmployee(b, 100)
}

func BenchmarkEmployeeFeatureTransformer_Transform_LargeComposites_1000elements(b *testing.B) {
	benchLargeTransformerEmployee(b, 1000)
}

func BenchmarkEmployeeFeatureTransformer_Transform_LargeComposites_10000elements(b *testing.B) {
	benchLargeTransformerEmployee(b, 10000)
}

func BenchmarkEmployeeFeatureTransformer_Transform_LargeComposites_100000elements(b *testing.B) {
	benchLargeTransformerEmployee(b, 100000)
}
