name: GitHub Clone Count for 14 days at every 8 hours

on:
  schedule:
    - cron: "0 */8 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get GitHub stats
        run: |
          curl --user "${{ github.actor }}:${{ secrets.SECRET_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/traffic/clones \
            > docs/githubstats.json  
          
      - name: Add to git repo
        run: |
          git add .
          git config --global user.name "GitHub Action - Github Counters"
          git config --global user.email "action@github.com"
          git commit -m "Automated clone.json update"
          
      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
